# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: /home/asanche4/Master/nanoupv2025/genesys_2_2024_1/genesys2_basic.srcs/sources_1/bd/system/ip/system_mdm_1_riscv_0/system_mdm_1_riscv_0.xci
# IP: The module: 'system_mdm_1_riscv_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/asanche4/Master/nanoupv2025/genesys_2_2024_1/genesys2_basic.gen/sources_1/bd/system/ip/system_mdm_1_riscv_0/system_mdm_1_riscv_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'system_mdm_1_riscv_0'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: /home/asanche4/Master/nanoupv2025/genesys_2_2024_1/genesys2_basic.gen/sources_1/bd/system/ip/system_mdm_1_riscv_0/system_mdm_1_riscv_0_ooc_trace.xdc
# XDC: The top module name and the constraint reference have the same name: 'system_mdm_1_riscv_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# IP: /home/asanche4/Master/nanoupv2025/genesys_2_2024_1/genesys2_basic.srcs/sources_1/bd/system/ip/system_mdm_1_riscv_0/system_mdm_1_riscv_0.xci
# IP: The module: 'system_mdm_1_riscv_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/asanche4/Master/nanoupv2025/genesys_2_2024_1/genesys2_basic.gen/sources_1/bd/system/ip/system_mdm_1_riscv_0/system_mdm_1_riscv_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'system_mdm_1_riscv_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: /home/asanche4/Master/nanoupv2025/genesys_2_2024_1/genesys2_basic.gen/sources_1/bd/system/ip/system_mdm_1_riscv_0/system_mdm_1_riscv_0_ooc_trace.xdc
# XDC: The top module name and the constraint reference have the same name: 'system_mdm_1_riscv_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet
