# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: imports/Downloads/Genesys-2-Master.xdc

# Block Designs: bd/system/system.bd
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==system || ORIG_REF_NAME==system} -quiet] -quiet

# IP: bd/system/ip/system_mig_7series_0_0/system_mig_7series_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==system_mig_7series_0_0 || ORIG_REF_NAME==system_mig_7series_0_0} -quiet] -quiet

# IP: bd/system/ip/system_dlmb_v10_0/system_dlmb_v10_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==system_dlmb_v10_0 || ORIG_REF_NAME==system_dlmb_v10_0} -quiet] -quiet

# IP: bd/system/ip/system_ilmb_v10_0/system_ilmb_v10_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==system_ilmb_v10_0 || ORIG_REF_NAME==system_ilmb_v10_0} -quiet] -quiet

# IP: bd/system/ip/system_dlmb_bram_if_cntlr_0/system_dlmb_bram_if_cntlr_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==system_dlmb_bram_if_cntlr_0 || ORIG_REF_NAME==system_dlmb_bram_if_cntlr_0} -quiet] -quiet

# IP: bd/system/ip/system_ilmb_bram_if_cntlr_0/system_ilmb_bram_if_cntlr_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==system_ilmb_bram_if_cntlr_0 || ORIG_REF_NAME==system_ilmb_bram_if_cntlr_0} -quiet] -quiet

# IP: bd/system/ip/system_lmb_bram_0/system_lmb_bram_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==system_lmb_bram_0 || ORIG_REF_NAME==system_lmb_bram_0} -quiet] -quiet

# IP: bd/system/ip/system_rst_mig_7series_0_100M_0/system_rst_mig_7series_0_100M_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==system_rst_mig_7series_0_100M_0 || ORIG_REF_NAME==system_rst_mig_7series_0_100M_0} -quiet] -quiet

# IP: bd/system/ip/system_axi_uartlite_0_0/system_axi_uartlite_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==system_axi_uartlite_0_0 || ORIG_REF_NAME==system_axi_uartlite_0_0} -quiet] -quiet

# IP: bd/system/ip/system_xbar_0/system_xbar_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==system_xbar_0 || ORIG_REF_NAME==system_xbar_0} -quiet] -quiet

# IP: bd/system/ip/system_microblaze_0_axi_periph_0/system_microblaze_0_axi_periph_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==system_microblaze_0_axi_periph_0 || ORIG_REF_NAME==system_microblaze_0_axi_periph_0} -quiet] -quiet

# IP: bd/system/ip/system_axi_intc_0_0/system_axi_intc_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==system_axi_intc_0_0 || ORIG_REF_NAME==system_axi_intc_0_0} -quiet] -quiet

# IP: bd/system/ip/system_axi_gpio_0_0/system_axi_gpio_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==system_axi_gpio_0_0 || ORIG_REF_NAME==system_axi_gpio_0_0} -quiet] -quiet

# IP: bd/system/ip/system_xlconcat_0_0/system_xlconcat_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==system_xlconcat_0_0 || ORIG_REF_NAME==system_xlconcat_0_0} -quiet] -quiet

# IP: bd/system/ip/system_axi_gpio_1_0/system_axi_gpio_1_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==system_axi_gpio_1_0 || ORIG_REF_NAME==system_axi_gpio_1_0} -quiet] -quiet

# IP: bd/system/ip/system_microblaze_0_0/system_microblaze_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==system_microblaze_0_0 || ORIG_REF_NAME==system_microblaze_0_0} -quiet] -quiet

# IP: bd/system/ip/system_mdm_0_0/system_mdm_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==system_mdm_0_0 || ORIG_REF_NAME==system_mdm_0_0} -quiet] -quiet

# IP: bd/system/ip/system_axi_timer_0_0_1/system_axi_timer_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==system_axi_timer_0_0 || ORIG_REF_NAME==system_axi_timer_0_0} -quiet] -quiet

# IP: bd/system/ip/system_axi_cdma_0_0_1/system_axi_cdma_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==system_axi_cdma_0_0 || ORIG_REF_NAME==system_axi_cdma_0_0} -quiet] -quiet

# IP: bd/system/ip/system_auto_us_0/system_auto_us_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==system_auto_us_0 || ORIG_REF_NAME==system_auto_us_0} -quiet] -quiet

# IP: bd/system/ip/system_auto_us_1/system_auto_us_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==system_auto_us_1 || ORIG_REF_NAME==system_auto_us_1} -quiet] -quiet

# IP: bd/system/ip/system_auto_ds_0/system_auto_ds_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==system_auto_ds_0 || ORIG_REF_NAME==system_auto_ds_0} -quiet] -quiet

# IP: bd/system/ip/system_auto_ds_1/system_auto_ds_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==system_auto_ds_1 || ORIG_REF_NAME==system_auto_ds_1} -quiet] -quiet

# IP: bd/system/ip/system_auto_ds_2/system_auto_ds_2.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==system_auto_ds_2 || ORIG_REF_NAME==system_auto_ds_2} -quiet] -quiet

# IP: bd/system/ip/system_auto_ds_3/system_auto_ds_3.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==system_auto_ds_3 || ORIG_REF_NAME==system_auto_ds_3} -quiet] -quiet

# IP: bd/system/ip/system_auto_ds_4_1/system_auto_ds_4.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==system_auto_ds_4 || ORIG_REF_NAME==system_auto_ds_4} -quiet] -quiet

# IP: bd/system/ip/system_auto_ds_5_1/system_auto_ds_5.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==system_auto_ds_5 || ORIG_REF_NAME==system_auto_ds_5} -quiet] -quiet

# IP: bd/system/ip/system_smartconnect_0_0/system_smartconnect_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==system_smartconnect_0_0 || ORIG_REF_NAME==system_smartconnect_0_0} -quiet] -quiet

# XDC: /home/asanche4/Master/nanoupv2025/genesys_2_2024_1/genesys2_basic.gen/sources_1/bd/system/system_ooc.xdc
