# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: /home/asanche4/Master/nanoupv2025/genesys_2_2024_1/genesys2_basic.srcs/sources_1/bd/system/ip/system_auto_ds_4_1/system_auto_ds_4.xci
# IP: The module: 'system_auto_ds_4' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/asanche4/Master/nanoupv2025/genesys_2_2024_1/genesys2_basic.gen/sources_1/bd/system/ip/system_auto_ds_4_1/system_auto_ds_4_clocks.xdc
# XDC: The top module name and the constraint reference have the same name: 'system_auto_ds_4'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: /home/asanche4/Master/nanoupv2025/genesys_2_2024_1/genesys2_basic.gen/sources_1/bd/system/ip/system_auto_ds_4_1/system_auto_ds_4_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'system_auto_ds_4'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# IP: /home/asanche4/Master/nanoupv2025/genesys_2_2024_1/genesys2_basic.srcs/sources_1/bd/system/ip/system_auto_ds_4_1/system_auto_ds_4.xci
# IP: The module: 'system_auto_ds_4' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/asanche4/Master/nanoupv2025/genesys_2_2024_1/genesys2_basic.gen/sources_1/bd/system/ip/system_auto_ds_4_1/system_auto_ds_4_clocks.xdc
# XDC: The top module name and the constraint reference have the same name: 'system_auto_ds_4'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: /home/asanche4/Master/nanoupv2025/genesys_2_2024_1/genesys2_basic.gen/sources_1/bd/system/ip/system_auto_ds_4_1/system_auto_ds_4_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'system_auto_ds_4'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet
